services:
  nginx:
    image: pablodroopy/cloudflared-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
    restart: unless-stopped
    env_file:
      - .env
    entrypoint: >
      /bin/sh -c "cloudflared update; cloudflared tunnel run --token $$CLOUDFLARED_TOKEN & \
        nginx -g 'daemon off;'"
